name: data-science
channels:
  - conda-forge
  - ioam
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - ipython
  - cartopy
  - geopandas
  - folium
  - geopy
  - holoviews
